### PR TITLE
Fix https://github.com/avishayil/react-native-user-avatar/issues/49

### PR DESCRIPTION
**Pull request by pqminh**
Extend useEffect to render the image in case it changes

### CODE REVIEW

**Comment by pqminh** [comment]
@avishayil Can you help me merge this!

**Comment by avishayil** [comment]
@wimvdb Do you have any idea what's going on with travis? I checked the PR on travis and it looks good, but GitHub is not updated. Webhook looks good too.
https://travis-ci.org/github/avishayil/react-native-user-avatar

**Comment by avishayil** [comment]
@juraam Can you please fix the errors in the build?

**Comment by avishayil** [comment]
Hi, please fix the tests and pull the changes from the base branch

**Comment by walidvb** [comment]
Hey, will this ever make it to master?

**Comment by avishayil** [comment]
Merged with https://github.com/avishayil/react-native-user-avatar/commit/d8786a7538468ff003f2531ae3c99820d3e2fcfb

**Pull request closed without merging**
